/**
 * Body weight, its trend, and what the food log says should have happened.
 *
 * Two things shape this whole screen. Weigh-ins are *sparse and irregular* —
 * this account has forty across eleven months, with gaps of months — so nothing
 * here may assume a reading per day, and the chart is drawn against a calendar
 * rather than against a list of samples. And a single reading is noise: a heavy
 * dinner and a dehydrated morning are two kilos apart on the same body, which
 * is why the figure quoted as "your weight" is the smoothed trend, and why a
 * reading that disagrees with both its neighbours is marked as the typo it
 * almost certainly is rather than being drawn as a real excursion.
 *
 * The weigh-ins are Garmin's. Only the goal is the app's own — the account
 * exposes no readable weight goal — and the UI says so where it's shown.
 */
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import {
  chatConfig,
  setWeightGoal,
  weight,
  weightSummary,
  type WeightPoint,
  type WeightReport,
} from "../lib/api";
import type { Point } from "../lib/chart";
import {
  ArrowRight,
  AxisLabels,
  Empty,
  ErrorNote,
  LineChart,
  Loading,
  Metric,
  MetricRow,
  PageHeader,
} from "../components/ui";
import { SpinnerIcon } from "../lib/icons";
import { RefreshButton } from "../components/Refresh";
import { DASH, num, parseLocal, shortDate, since } from "../lib/format";

const DAYS = 180;

/** Beyond this, the newest reading is old enough that the trend is a memory. */
const STALE_DAYS = 21;

const kg = (v: number | null | undefined) =>
  v == null ? DASH : `${v.toFixed(1)} kg`;

/** Signed, with the sign carrying the meaning rather than a colour alone. */
function signedKg(v: number | null | undefined, digits = 1): string {
  if (v == null) return DASH;
  const s = v.toFixed(digits);
  return v > 0 ? `+${s}` : s;
}

export function Weight() {
  const { data, isLoading, error } = useQuery({
    queryKey: ["weight", DAYS],
    queryFn: () => weight(DAYS),
  });

  if (isLoading) return <Loading />;
  if (error) return <ErrorNote error={error} />;

  const report = data;

  if (!report || report.count === 0) {
    return (
      <div>
        <PageHeader
          eyebrow="From Garmin"
          title="Weight"
          action={<RefreshButton />}
        />
        <Empty
          title={
            report?.latestDate
              ? "No weigh-ins in the last six months."
              : "No weigh-ins on this account."
          }
          body={
            <>
              This screen reads what Garmin holds — it never writes a weight and
              never invents one. Weigh-ins reach Garmin from a connected scale,
              from the Connect app's own entry screen, or from an integration
              like MyFitnessPal.{" "}
              {report?.latestDate
                ? `The most recent one on the account is from ${report.latestDate}.`
                : "Record one and it appears here on the next sync."}
            </>
          }
          action={<FoodLink />}
        />
      </div>
    );
  }

  return (
    <div className="screen">
      <PageHeader
        eyebrow={`Last ${DAYS} days · ${report.count} ${report.count === 1 ? "weigh-in" : "weigh-ins"}`}
        title="Weight"
        action={<RefreshButton />}
        // The written summary directly below is this screen's lede, so the
        // header shouldn't reserve its usual gap on top of it.
        space={28}
      />

      <Summary report={report} />
      <Numbers report={report} />
      <Chart report={report} />
      <Energy report={report} />
      <Goal report={report} />
      <ByDay points={report.points} />

      <div style={{ marginTop: 66 }}>
        <FoodLink />
      </div>
    </div>
  );
}

/* ---------------------------------------------------------------- summary --- */

/**
 * The written opening. Generated by the configured model from the same report
 * the rest of the screen draws, and then *kept* — regenerating on every visit
 * would bill a request for walking back to a page whose numbers haven't moved,
 * so the backend stores it against a fingerprint of the figures it describes
 * and only rewrites when one of them changes.
 */
function Summary({ report }: { report: WeightReport }) {
  const qc = useQueryClient();
  const config = useQuery({ queryKey: ["chatConfig"], queryFn: chatConfig });

  // The summary is only asked for once a provider exists. Without one the
  // request would fail with a message about Settings, which is a worse way to
  // say "not set up" than simply not asking.
  const ready = !!config.data?.provider;
  const summary = useQuery({
    queryKey: ["weightSummary", DAYS],
    queryFn: () => weightSummary(DAYS),
    enabled: ready,
    staleTime: Infinity,
    retry: false,
  });

  const regenerate = useMutation({
    mutationFn: () => weightSummary(DAYS, true),
    onSuccess: (fresh) => qc.setQueryData(["weightSummary", DAYS], fresh),
  });

  const body = (() => {
    if (config.isLoading) return null;
    if (!ready) return <Unconfigured report={report} />;
    if (summary.isLoading || regenerate.isPending) return <Writing />;
    if (summary.error) return <Unwritten error={summary.error} />;
    return summary.data?.text;
  })();

  if (body == null) return <div style={{ height: 96 }} />;

  return (
    <div style={{ marginBottom: 46 }}>
      {/* Styled exactly like `PageHeader`'s own lede, because that is what it
          is — this screen's opening paragraph, which happens to be written by
          a model rather than by hand. The serif is the app's heading face;
          prose is sans everywhere else and had no business differing here. */}
      <p className="lede" style={{ fontSize: "var(--fs-lg)", lineHeight: 1.7, maxWidth: "62ch" }}>
        {body}
      </p>
      {ready && summary.data && !regenerate.isPending && (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 14,
            marginTop: 16,
            fontSize: "var(--fs-caption)",
            color: "var(--faint)",
          }}
        >
          {/* Said plainly, because the prose can be days old: it's rewritten
              when the numbers move, not when the page is opened. */}
          <span>Written {since(summary.data.generatedAt)} from your last {DAYS} days</span>
          <button
            className="quiet"
            onClick={() => regenerate.mutate()}
            style={{ fontSize: "var(--fs-caption)", color: "var(--mut)" }}
            title="Write it again from the same data"
          >
            Rewrite
          </button>
        </div>
      )}
    </div>
  );
}

function Writing() {
  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 10, color: "var(--mut)" }}>
      <SpinnerIcon size={17} className="spin" aria-hidden />
      Reading your weigh-ins…
    </span>
  );
}

/**
 * No model configured. The screen still has to open with something, so it opens
 * with the same facts stated plainly — the numbers below are all computed
 * locally and don't need a model at all.
 */
function Unconfigured({ report }: { report: WeightReport }) {
  return (
    <>
      {plainReading(report)}{" "}
      <Link
        to="/settings"
        style={{ color: "var(--mut)", textDecoration: "underline", textUnderlineOffset: 3 }}
      >
        Set up a model in Settings
      </Link>{" "}
      and this opens with a written read of it instead.
    </>
  );
}

function Unwritten({ error }: { error: unknown }) {
  return (
    <span style={{ color: "var(--mut)" }}>
      The model couldn't be reached, so this page is just its numbers today.{" "}
      <span style={{ fontSize: "var(--fs-base)", color: "var(--faint)" }}>
        ({error instanceof Error ? error.message : String(error)})
      </span>
    </span>
  );
}

/**
 * The fallback opening sentence, in the same voice the model is asked for.
 * Deliberately refuses to describe a direction the data doesn't support.
 */
function plainReading(r: WeightReport): string {
  const stale = r.daysSinceLatest != null && r.daysSinceLatest > STALE_DAYS;
  if (stale) {
    return `Your last weigh-in was ${r.daysSinceLatest} days ago, at ${kg(r.latestKg)}, which is too long ago for the trend to describe you now.`;
  }
  if (r.rateKgPerWeek == null) {
    return `The trend sits at ${kg(r.trendKg)}, from ${r.count} ${r.count === 1 ? "weigh-in" : "weigh-ins"} — not yet enough history, spread widely enough, to call a direction.`;
  }
  const dir = r.rateKgPerWeek < 0 ? "down" : "up";
  return `The trend sits at ${kg(r.trendKg)}, moving ${dir} about ${Math.abs(r.rateKgPerWeek).toFixed(2)} kg a week across ${r.count} weigh-ins.`;
}

/* ---------------------------------------------------------------- numbers --- */

function Numbers({ report }: { report: WeightReport }) {
  const stale = report.daysSinceLatest != null && report.daysSinceLatest > STALE_DAYS;

  return (
    <>
      <MetricRow style={{ marginBottom: 10 }}>
        {/* The trend, not the last reading: a single weigh-in is noise around
            this, and quoting it as "your weight" makes the noise the headline. */}
        <Metric value={kg(report.trendKg)} label="Trend" />
        <Metric
          value={signedKg(report.changeKg)}
          label={report.spanDays != null ? `Over ${report.spanDays} days` : "Change"}
        />
        <Metric
          value={report.rateKgPerWeek != null ? signedKg(report.rateKgPerWeek, 2) : DASH}
          label="Per week"
        />
        <Metric value={report.bmi != null ? report.bmi.toFixed(1) : DASH} label="BMI" />
      </MetricRow>

      <p style={{ fontSize: "var(--fs-small)", color: "var(--faint)", margin: "0 0 8px", maxWidth: "62ch" }}>
        Trend is a time-weighted smoothing of your weigh-ins, so an irregular
        gap between two of them doesn't count the same as a day.{" "}
        {report.rateKgPerWeek == null &&
          "The weekly rate needs at least three clean readings spread over a fortnight, which isn't there yet. "}
        {report.bmi != null && report.heightCm != null
          ? `BMI is against the ${report.heightCm} cm on your Garmin profile — it knows nothing about how the weight is made up.`
          : "BMI needs a height on your Garmin profile, which isn't set."}
        {stale &&
          ` Your last weigh-in was ${report.daysSinceLatest} days ago, so treat all of this as describing then, not now.`}
      </p>
    </>
  );
}

/* ------------------------------------------------------------------ chart --- */

const DAY_MS = 86_400_000;

/**
 * Weigh-ins plotted against the calendar, not against their own index.
 *
 * This is the whole reason the chart builds its own daily arrays: the shared
 * `LineChart` spaces points evenly, so handing it the forty samples directly
 * would draw a three-month gap and a one-day gap the same width and turn a
 * flat winter into a cliff.
 *
 * Outliers are left out of both series. Including one drags the y-range far
 * enough to flatten every real movement into a straight line — they're still
 * listed, and flagged, in the table below.
 */
function Chart({ report }: { report: WeightReport }) {
  const clean = report.points.filter((p) => !p.outlier);
  if (clean.length < 2) return null;

  const start = parseLocal(clean[0].date);
  const end = parseLocal(clean[clean.length - 1].date);
  if (!start || !end) return null;

  const span = Math.max(1, Math.round((end.getTime() - start.getTime()) / DAY_MS));
  const index = (date: string) => {
    const d = parseLocal(date);
    return d ? Math.round((d.getTime() - start.getTime()) / DAY_MS) : null;
  };

  // One slot per calendar day. Readings land on their own day and nothing else
  // is filled in, so the sparsity is visible rather than smoothed over.
  const raw: Point[] = Array(span + 1).fill(null);
  const anchors: Array<[number, number]> = [];
  for (const p of clean) {
    const i = index(p.date);
    if (i == null) continue;
    raw[i] = p.kg;
    if (p.trendKg != null) anchors.push([i, p.trendKg]);
  }

  // The trend is drawn as one continuous line, interpolated across the gaps —
  // it's a running estimate that exists between weigh-ins, unlike the readings.
  const trend: Point[] = Array(span + 1).fill(null);
  for (let a = 0; a < anchors.length - 1; a++) {
    const [x0, y0] = anchors[a];
    const [x1, y1] = anchors[a + 1];
    for (let x = x0; x <= x1; x++) {
      trend[x] = x1 === x0 ? y0 : y0 + ((y1 - y0) * (x - x0)) / (x1 - x0);
    }
  }

  return (
    <>
      <div className="eyebrow" style={{ margin: "64px 0 16px" }}>
        Trend against the readings
      </div>
      {/* Shared scale: the point is how far each reading sits from the trend,
          which two independent scales would erase. */}
      <LineChart
        shareScale
        series={[
          { values: trend, stroke: "var(--acc)", width: 1.6, fill: true, name: "Trend", format: kg },
          { values: raw, stroke: "var(--mut)", width: 1.2, name: "Weigh-in", format: kg },
        ]}
        // One slot per calendar day, so the readout can name the day the
        // pointer is actually over rather than the nearest reading's.
        labels={raw.map((_, i) => {
          // Stepped by date rather than by 86 400 000 ms — an hour of daylight
          // saving inside the span would slide every label after it by a day.
          const d = new Date(start);
          d.setDate(d.getDate() + i);
          return shortDate(d);
        })}
      />
      <AxisLabels labels={[shortDate(start), shortDate(end)]} />
      <div style={{ display: "flex", gap: 20, fontSize: "var(--fs-caption)", color: "var(--faint)", marginTop: 10 }}>
        <span style={{ color: "var(--acc)" }}>— Trend</span>
        <span>· Weigh-ins</span>
        <span>Spaced by date, so the gaps are real.</span>
      </div>
    </>
  );
}

/* ----------------------------------------------------------------- energy --- */

/**
 * The calorie log against the scale.
 *
 * The two rarely agree, and the gap is the interesting part — but only once
 * it's clear how much of the span the food log actually covers. A month with
 * six logged days can't predict a month of weight change, and this section
 * leads with that rather than burying it.
 */
function Energy({ report }: { report: WeightReport }) {
  const e = report.energy;
  if (!e) return null;

  const thin = e.coveragePct < 60;
  const predicted = e.predictedChangeKg;
  const actual = e.actualChangeKg;

  return (
    <>
      <div className="eyebrow" style={{ margin: "66px 0 16px" }}>
        Calories against the scale
      </div>

      <MetricRow gap={48} style={{ marginBottom: 14 }}>
        <Metric size={30} value={signedKg(predicted, 2)} label="Log predicts" />
        <Metric size={30} value={signedKg(actual, 1)} label="Scale says" />
        <Metric
          size={30}
          value={`${Math.round(e.coveragePct)}%`}
          label="Days logged"
          accent={thin}
        />
      </MetricRow>

      <p style={{ fontSize: "var(--fs-base)", lineHeight: 1.65, color: "var(--mut)", maxWidth: "62ch" }}>
        Across the {e.spanDays} days your weigh-ins span, {e.loggedDays} carried a
        food log. Those days come to {num(Math.round(e.balanceKcal))} kcal, which is{" "}
        {signedKg(predicted, 2)} at the textbook 7,700 kcal per kilogram.{" "}
        {thin
          ? "That figure covers only the logged days — it is not scaled up to the rest, because inventing the missing ones would make it a prediction about data that doesn't exist. Most of any gap between the two numbers above is missing log, not metabolism."
          : "The two won't match exactly — 7,700 kcal per kilogram assumes what's lost is mostly fat, and the scale carries water either way — but at this coverage the direction is worth believing."}
      </p>
    </>
  );
}

/* ------------------------------------------------------------------- goal --- */

/**
 * The one figure on this screen that isn't Garmin's.
 *
 * Garmin exposes no readable weight goal on this account, so the target is
 * stored locally and labelled as such — the alternative was showing an
 * app-invented number in the same voice as the synced ones.
 */
function Goal({ report }: { report: WeightReport }) {
  const qc = useQueryClient();
  const goal = report.goal;
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(goal ? String(goal.targetKg) : "");

  const save = useMutation({
    mutationFn: (target: number | null) => setWeightGoal(target),
    onSuccess: () => {
      setEditing(false);
      qc.invalidateQueries({ queryKey: ["weight"] });
      // The prose describes the goal, so it has to be rewritten against the
      // new one rather than kept from the old.
      qc.invalidateQueries({ queryKey: ["weightSummary"] });
    },
  });

  const commit = () => {
    const parsed = Number.parseFloat(draft.replace(",", "."));
    save.mutate(Number.isFinite(parsed) && parsed > 0 ? parsed : null);
  };

  return (
    <>
      <div className="eyebrow" style={{ margin: "66px 0 16px" }}>
        Goal{" "}
        <span
          style={{ color: "var(--faint)", letterSpacing: 0, textTransform: "none" }}
          title="Garmin's API exposes no weight goal — nothing to read and nothing to write it to — so this one is stored locally"
        >
            kept in this app; Garmin has no weight goal to sync
        </span>
      </div>

      {editing || !goal ? (
        <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
          {/* The app's one input treatment, same as the key and search fields
              in Settings. `.input` is width:100% by design, so the width this
              field wants is set on a wrapper rather than by overriding it. */}
          <div style={{ width: 120, flex: "none" }}>
            <input
              className="input"
              type="text"
              inputMode="decimal"
              value={draft}
              autoFocus={editing}
              placeholder="80"
              onChange={(e) => setDraft(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && commit()}
              aria-label="Target weight in kilograms"
            />
          </div>
          <span style={{ fontSize: "var(--fs-small)", color: "var(--faint)" }}>kg</span>
          <button className="cta" onClick={commit} disabled={save.isPending}>
            {save.isPending ? "Saving…" : "Save"}
          </button>
          {goal && (
            <button className="quiet" onClick={() => setEditing(false)} style={{ fontSize: "var(--fs-caption)" }}>
              Cancel
            </button>
          )}
          {!goal && !editing && (
            <span style={{ fontSize: "var(--fs-small)", color: "var(--faint)" }}>
              Optional. With one set, this projects an arrival date from your trend.
            </span>
          )}
        </div>
      ) : (
        <>
          <MetricRow gap={48} style={{ marginBottom: 14 }}>
            <Metric size={30} value={kg(goal.targetKg)} label="Target" />
            <Metric size={30} value={signedKg(goal.deltaKg)} label="To go" />
            <Metric
              size={30}
              value={
                goal.etaDate
                  ? shortDate(parseLocal(goal.etaDate) ?? new Date(goal.etaDate))
                  : DASH
              }
              label="At this rate"
            />
          </MetricRow>
          <p style={{ fontSize: "var(--fs-base)", lineHeight: 1.65, color: "var(--mut)", maxWidth: "62ch" }}>
            {goal.etaDays != null ? (
              <>
                About {goal.etaDays} days away if the current rate holds — which
                is a big if over that span, and the projection is only ever as
                good as the trend behind it.
              </>
            ) : (
              <>
                No arrival date: the trend is either flat or pointing away from
                this target, and a date computed from that would be fiction. It
                appears once the trend moves toward {goal.targetKg} kg.
              </>
            )}{" "}
            <button
              className="quiet"
              onClick={() => {
                setDraft(String(goal.targetKg));
                setEditing(true);
              }}
              style={{ fontSize: "var(--fs-base)", color: "var(--mut)", textDecoration: "underline", textUnderlineOffset: 3 }}
            >
              Change
            </button>
          </p>
        </>
      )}
    </>
  );
}

/* ----------------------------------------------------------------- by day --- */

function ByDay({ points }: { points: WeightPoint[] }) {
  // Newest first here, unlike the chart: a list is read top-down and the most
  // recent weigh-in is the one you came to see.
  const rows = [...points].reverse();

  return (
    <>
      <div className="eyebrow" style={{ margin: "66px 0 6px" }}>
        Every weigh-in
      </div>
      <div>
        {rows.map((p) => (
          <Row key={p.date} point={p} />
        ))}
      </div>
    </>
  );
}

function Row({ point }: { point: WeightPoint }) {
  const d = parseLocal(point.date);
  const drift =
    point.trendKg != null && !point.outlier ? point.kg - point.trendKg : null;

  return (
    <div className="row-static" style={{ justifyContent: "space-between" }}>
      <span style={{ width: 96, flex: "none" }}>{d ? shortDate(d) : point.date}</span>

      <span
        className="mono"
        style={{ width: 84, textAlign: "right", color: point.outlier ? "var(--faint)" : undefined }}
      >
        {point.kg.toFixed(1)}
      </span>

      <span className="mono" style={{ width: 84, textAlign: "right", color: "var(--mut)" }}>
        {point.trendKg != null ? point.trendKg.toFixed(1) : DASH}
      </span>

      {/* How far this reading sat from the trend — the size of the daily noise,
          which is the thing that makes one reading a bad headline. */}
      <span
        className="mono"
        style={{ width: 76, textAlign: "right", color: "var(--faint)", fontSize: "var(--fs-small)" }}
      >
        {drift != null ? signedKg(drift) : ""}
      </span>

      <span
        style={{
          width: 130,
          textAlign: "right",
          fontSize: "var(--fs-caption)",
          color: point.outlier ? "var(--acc)" : "var(--faint)",
        }}
        title={point.outlier ? "Disagrees with both neighbours by more than a body can move" : undefined}
      >
        {point.outlier ? "looks like a typo" : sourceLabel(point.source)}
      </span>
    </div>
  );
}

/** Garmin's source codes, in words. Unknown ones pass through as they are. */
function sourceLabel(source: string | null): string {
  switch (source) {
    case "MFP":
      return "MyFitnessPal";
    case "MANUAL":
      return "entered by hand";
    case "USER_SETTING":
      return "from your profile";
    default:
      return source?.toLowerCase() ?? "";
  }
}

function FoodLink() {
  return (
    <Link
      to="/food"
      className="row"
      style={{ display: "inline-flex", alignItems: "center", gap: 9, fontSize: "var(--fs-base)" }}
    >
      What you ate against what you burned
      <ArrowRight />
    </Link>
  );
}
